# config.yaml
data:
  topo_path: data/topo_graph.json
  alarm_path: data/alarms.json
  batch_size: 16
  max_len: 16
  window_milliseconds: 5000
  step_milliseconds: 500
  num_train: 0.7
  num_val: 0.2
  num_test: 0.1

model:
  gnn:
    hidden_channels: 64
    num_layers: 3
    dropout: 0.3
    pretrained_path: data/processed/pretrained_gnn.pth
  transformer:
    emb_dim: 64
    nhead: 4
    hid_dim: 128
    nlayers: 2
    max_len: 16
    dropout: 0.1

training:
  epochs: 100
  stage1_epochs: 10
  lr: 1e-3
  lr_true: 5e-4
  weight_decay: 1e-5
  lr_step_size: 10
  early_stop_patience : 7
  root_focal_alpha: 0.4
  root_focal_gamma: 2.0
  true_focal_alpha: 0.65
  true_focal_gamma: 2.5
  true_loss_weight: 2.2